DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    duration     BIGINT,
    name         VARCHAR(255),
    description  VARCHAR(255),
    release_date date,
    genre        VARCHAR(255),
    mpa          VARCHAR(255),
    CONSTRAINT pk_film PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    login    VARCHAR(255),
    name     VARCHAR(255),
    birthday date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE friends
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    friend_id BIGINT,
    user_id   BIGINT,
    CONSTRAINT pk_friends PRIMARY KEY (id)
);

ALTER TABLE friends
    ADD CONSTRAINT FK_FRIENDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE likes
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    film_id BIGINT,
    user_id BIGINT,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_FILM FOREIGN KEY (film_id) REFERENCES films (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

