version: '3.1'
services:
  film-server:
    build: ./
    container_name: film-server
    ports:
      - "8080:8080"
    depends_on:
      - film-db
    environment:
      - POSTGRES_USER=film
      - POSTGRES_PASSWORD=film
      - SPRING_DATASOURCE_URL=jdbc:postgresql://film-db:5432/film

  film-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=film
      - POSTGRES_USER=film
      - POSTGRES_PASSWORD=film